// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: kama_chat.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_kama_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PushRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Ret           int32                  `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_kama_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Response) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type GetMessageBySeqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartSeq      int64                  `protobuf:"varint,2,opt,name=start_seq,json=startSeq,proto3" json:"start_seq,omitempty"`
	EndSeq        int64                  `protobuf:"varint,3,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageBySeqRequest) Reset() {
	*x = GetMessageBySeqRequest{}
	mi := &file_kama_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageBySeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageBySeqRequest) ProtoMessage() {}

func (x *GetMessageBySeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageBySeqRequest.ProtoReflect.Descriptor instead.
func (*GetMessageBySeqRequest) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessageBySeqRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMessageBySeqRequest) GetStartSeq() int64 {
	if x != nil {
		return x.StartSeq
	}
	return 0
}

func (x *GetMessageBySeqRequest) GetEndSeq() int64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

type ResponseForGetMessageBySeq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageList   []*MessageResponse     `protobuf:"bytes,1,rep,name=message_list,json=messageList,proto3" json:"message_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseForGetMessageBySeq) Reset() {
	*x = ResponseForGetMessageBySeq{}
	mi := &file_kama_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForGetMessageBySeq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForGetMessageBySeq) ProtoMessage() {}

func (x *ResponseForGetMessageBySeq) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForGetMessageBySeq.ProtoReflect.Descriptor instead.
func (*ResponseForGetMessageBySeq) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseForGetMessageBySeq) GetMessageList() []*MessageResponse {
	if x != nil {
		return x.MessageList
	}
	return nil
}

type MessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgId          int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Seq            int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	SendId         int64                  `protobuf:"varint,4,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`
	Type           int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Content        string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Status         int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	SendTime       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_kama_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{4}
}

func (x *MessageResponse) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MessageResponse) GetSendId() int64 {
	if x != nil {
		return x.SendId
	}
	return 0
}

func (x *MessageResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MessageResponse) GetSendTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SendTime
	}
	return nil
}

type UserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_kama_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{5}
}

func (x *UserIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ConversationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Avatar         string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Type           int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Member         int32                  `protobuf:"varint,4,opt,name=member,proto3" json:"member,omitempty"`
	RecentMsgTime  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=recent_msg_time,json=recentMsgTime,proto3" json:"recent_msg_time,omitempty"`
	LastReadSeq    int64                  `protobuf:"varint,6,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	NotifyType     int32                  `protobuf:"varint,7,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"`
	IsTop          int32                  `protobuf:"varint,8,opt,name=is_top,json=isTop,proto3" json:"is_top,omitempty"`
	Name           string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationResponse) Reset() {
	*x = ConversationResponse{}
	mi := &file_kama_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationResponse) ProtoMessage() {}

func (x *ConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationResponse.ProtoReflect.Descriptor instead.
func (*ConversationResponse) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ConversationResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ConversationResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ConversationResponse) GetMember() int32 {
	if x != nil {
		return x.Member
	}
	return 0
}

func (x *ConversationResponse) GetRecentMsgTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RecentMsgTime
	}
	return nil
}

func (x *ConversationResponse) GetLastReadSeq() int64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *ConversationResponse) GetNotifyType() int32 {
	if x != nil {
		return x.NotifyType
	}
	return 0
}

func (x *ConversationResponse) GetIsTop() int32 {
	if x != nil {
		return x.IsTop
	}
	return 0
}

func (x *ConversationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponseForGetConversationList struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	ConversationList []*ConversationResponse `protobuf:"bytes,1,rep,name=conversation_list,json=conversationList,proto3" json:"conversation_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseForGetConversationList) Reset() {
	*x = ResponseForGetConversationList{}
	mi := &file_kama_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForGetConversationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForGetConversationList) ProtoMessage() {}

func (x *ResponseForGetConversationList) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForGetConversationList.ProtoReflect.Descriptor instead.
func (*ResponseForGetConversationList) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseForGetConversationList) GetConversationList() []*ConversationResponse {
	if x != nil {
		return x.ConversationList
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_kama_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Telephone     string                 `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	Birthday      string                 `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsAdmin       int32                  `protobuf:"varint,10,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	Status        int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_kama_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{9}
}

func (x *UserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserResponse) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *UserResponse) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserResponse) GetIsAdmin() int32 {
	if x != nil {
		return x.IsAdmin
	}
	return 0
}

func (x *UserResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telephone     string                 `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_kama_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{10}
}

func (x *LoginRequest) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespondForGetFriendList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendList    []*UserResponse        `protobuf:"bytes,1,rep,name=friend_list,json=friendList,proto3" json:"friend_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondForGetFriendList) Reset() {
	*x = RespondForGetFriendList{}
	mi := &file_kama_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondForGetFriendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondForGetFriendList) ProtoMessage() {}

func (x *RespondForGetFriendList) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondForGetFriendList.ProtoReflect.Descriptor instead.
func (*RespondForGetFriendList) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{11}
}

func (x *RespondForGetFriendList) GetFriendList() []*UserResponse {
	if x != nil {
		return x.FriendList
	}
	return nil
}

type ApplyFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyFriendRequest) Reset() {
	*x = ApplyFriendRequest{}
	mi := &file_kama_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyFriendRequest) ProtoMessage() {}

func (x *ApplyFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyFriendRequest.ProtoReflect.Descriptor instead.
func (*ApplyFriendRequest) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{12}
}

func (x *ApplyFriendRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApplyFriendRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ApplyFriendRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int64                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_kama_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyResponse) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ApplyResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ApplyResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ApplyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResponseForApplyList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyList     []*ApplyResponse       `protobuf:"bytes,1,rep,name=apply_list,json=applyList,proto3" json:"apply_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseForApplyList) Reset() {
	*x = ResponseForApplyList{}
	mi := &file_kama_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseForApplyList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseForApplyList) ProtoMessage() {}

func (x *ResponseForApplyList) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseForApplyList.ProtoReflect.Descriptor instead.
func (*ResponseForApplyList) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ResponseForApplyList) GetApplyList() []*ApplyResponse {
	if x != nil {
		return x.ApplyList
	}
	return nil
}

type RespondToApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToApply) Reset() {
	*x = RespondToApply{}
	mi := &file_kama_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToApply) ProtoMessage() {}

func (x *RespondToApply) ProtoReflect() protoreflect.Message {
	mi := &file_kama_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToApply.ProtoReflect.Descriptor instead.
func (*RespondToApply) Descriptor() ([]byte, []int) {
	return file_kama_chat_proto_rawDescGZIP(), []int{15}
}

func (x *RespondToApply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RespondToApply) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

var File_kama_chat_proto protoreflect.FileDescriptor

const file_kama_chat_proto_rawDesc = "" +
	"\n" +
	"\x0fkama_chat.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\vPushRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\".\n" +
	"\bResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x10\n" +
	"\x03ret\x18\x02 \x01(\x05R\x03ret\"g\n" +
	"\x16GetMessageBySeqRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tstart_seq\x18\x02 \x01(\x03R\bstartSeq\x12\x17\n" +
	"\aend_seq\x18\x03 \x01(\x03R\x06endSeq\"T\n" +
	"\x1aResponseForGetMessageBySeq\x126\n" +
	"\fmessage_list\x18\x01 \x03(\v2\x13.pb.MessageResponseR\vmessageList\"\xfb\x01\n" +
	"\x0fMessageResponse\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x17\n" +
	"\asend_id\x18\x04 \x01(\x03R\x06sendId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x127\n" +
	"\tsend_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bsendTime\"(\n" +
	"\rUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xb7\x02\n" +
	"\x14ConversationResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x16\n" +
	"\x06member\x18\x04 \x01(\x05R\x06member\x12B\n" +
	"\x0frecent_msg_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rrecentMsgTime\x12\"\n" +
	"\rlast_read_seq\x18\x06 \x01(\x03R\vlastReadSeq\x12\x1f\n" +
	"\vnotify_type\x18\a \x01(\x05R\n" +
	"notifyType\x12\x15\n" +
	"\x06is_top\x18\b \x01(\x05R\x05isTop\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\"g\n" +
	"\x1eResponseForGetConversationList\x12E\n" +
	"\x11conversation_list\x18\x01 \x03(\v2\x18.pb.ConversationResponseR\x10conversationList\"g\n" +
	"\x0fRegisterRequest\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"\xb3\x02\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1c\n" +
	"\ttelephone\x18\x03 \x01(\tR\ttelephone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature\x12\x1a\n" +
	"\bbirthday\x18\b \x01(\tR\bbirthday\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x19\n" +
	"\bis_admin\x18\n" +
	" \x01(\x05R\aisAdmin\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\"H\n" +
	"\fLoginRequest\x12\x1c\n" +
	"\ttelephone\x18\x01 \x01(\tR\ttelephone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"L\n" +
	"\x17RespondForGetFriendList\x121\n" +
	"\vfriend_list\x18\x01 \x03(\v2\x10.pb.UserResponseR\n" +
	"friendList\"d\n" +
	"\x12ApplyFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"z\n" +
	"\rApplyResponse\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x03R\bfriendId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"H\n" +
	"\x14ResponseForApplyList\x120\n" +
	"\n" +
	"apply_list\x18\x01 \x03(\v2\x11.pb.ApplyResponseR\tapplyList\"F\n" +
	"\x0eRespondToApply\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId2/\n" +
	"\x04Push\x12'\n" +
	"\x04push\x12\x0f.pb.PushRequest\x1a\f.pb.Response\"\x002\xfe\x03\n" +
	"\bKamaChat\x12O\n" +
	"\x0fgetMessageBySeq\x12\x1a.pb.GetMessageBySeqRequest\x1a\x1e.pb.ResponseForGetMessageBySeq\"\x00\x12N\n" +
	"\x13getConversationList\x12\x11.pb.UserIdRequest\x1a\".pb.ResponseForGetConversationList\"\x00\x123\n" +
	"\bregister\x12\x13.pb.RegisterRequest\x1a\x10.pb.UserResponse\"\x00\x12-\n" +
	"\x05login\x12\x10.pb.LoginRequest\x1a\x10.pb.UserResponse\"\x00\x12A\n" +
	"\rgetFriendList\x12\x11.pb.UserIdRequest\x1a\x1b.pb.RespondForGetFriendList\"\x00\x125\n" +
	"\vapplyFriend\x12\x16.pb.ApplyFriendRequest\x1a\f.pb.Response\"\x00\x12=\n" +
	"\fgetApplyList\x12\x11.pb.UserIdRequest\x1a\x18.pb.ResponseForApplyList\"\x00\x124\n" +
	"\x0erespondToApply\x12\x12.pb.RespondToApply\x1a\f.pb.Response\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_kama_chat_proto_rawDescOnce sync.Once
	file_kama_chat_proto_rawDescData []byte
)

func file_kama_chat_proto_rawDescGZIP() []byte {
	file_kama_chat_proto_rawDescOnce.Do(func() {
		file_kama_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kama_chat_proto_rawDesc), len(file_kama_chat_proto_rawDesc)))
	})
	return file_kama_chat_proto_rawDescData
}

var file_kama_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_kama_chat_proto_goTypes = []any{
	(*PushRequest)(nil),                    // 0: pb.PushRequest
	(*Response)(nil),                       // 1: pb.Response
	(*GetMessageBySeqRequest)(nil),         // 2: pb.GetMessageBySeqRequest
	(*ResponseForGetMessageBySeq)(nil),     // 3: pb.ResponseForGetMessageBySeq
	(*MessageResponse)(nil),                // 4: pb.MessageResponse
	(*UserIdRequest)(nil),                  // 5: pb.UserIdRequest
	(*ConversationResponse)(nil),           // 6: pb.ConversationResponse
	(*ResponseForGetConversationList)(nil), // 7: pb.ResponseForGetConversationList
	(*RegisterRequest)(nil),                // 8: pb.RegisterRequest
	(*UserResponse)(nil),                   // 9: pb.UserResponse
	(*LoginRequest)(nil),                   // 10: pb.LoginRequest
	(*RespondForGetFriendList)(nil),        // 11: pb.RespondForGetFriendList
	(*ApplyFriendRequest)(nil),             // 12: pb.ApplyFriendRequest
	(*ApplyResponse)(nil),                  // 13: pb.ApplyResponse
	(*ResponseForApplyList)(nil),           // 14: pb.ResponseForApplyList
	(*RespondToApply)(nil),                 // 15: pb.RespondToApply
	(*timestamppb.Timestamp)(nil),          // 16: google.protobuf.Timestamp
}
var file_kama_chat_proto_depIdxs = []int32{
	4,  // 0: pb.ResponseForGetMessageBySeq.message_list:type_name -> pb.MessageResponse
	16, // 1: pb.MessageResponse.send_time:type_name -> google.protobuf.Timestamp
	16, // 2: pb.ConversationResponse.recent_msg_time:type_name -> google.protobuf.Timestamp
	6,  // 3: pb.ResponseForGetConversationList.conversation_list:type_name -> pb.ConversationResponse
	9,  // 4: pb.RespondForGetFriendList.friend_list:type_name -> pb.UserResponse
	13, // 5: pb.ResponseForApplyList.apply_list:type_name -> pb.ApplyResponse
	0,  // 6: pb.Push.push:input_type -> pb.PushRequest
	2,  // 7: pb.KamaChat.getMessageBySeq:input_type -> pb.GetMessageBySeqRequest
	5,  // 8: pb.KamaChat.getConversationList:input_type -> pb.UserIdRequest
	8,  // 9: pb.KamaChat.register:input_type -> pb.RegisterRequest
	10, // 10: pb.KamaChat.login:input_type -> pb.LoginRequest
	5,  // 11: pb.KamaChat.getFriendList:input_type -> pb.UserIdRequest
	12, // 12: pb.KamaChat.applyFriend:input_type -> pb.ApplyFriendRequest
	5,  // 13: pb.KamaChat.getApplyList:input_type -> pb.UserIdRequest
	15, // 14: pb.KamaChat.respondToApply:input_type -> pb.RespondToApply
	1,  // 15: pb.Push.push:output_type -> pb.Response
	3,  // 16: pb.KamaChat.getMessageBySeq:output_type -> pb.ResponseForGetMessageBySeq
	7,  // 17: pb.KamaChat.getConversationList:output_type -> pb.ResponseForGetConversationList
	9,  // 18: pb.KamaChat.register:output_type -> pb.UserResponse
	9,  // 19: pb.KamaChat.login:output_type -> pb.UserResponse
	11, // 20: pb.KamaChat.getFriendList:output_type -> pb.RespondForGetFriendList
	1,  // 21: pb.KamaChat.applyFriend:output_type -> pb.Response
	14, // 22: pb.KamaChat.getApplyList:output_type -> pb.ResponseForApplyList
	1,  // 23: pb.KamaChat.respondToApply:output_type -> pb.Response
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kama_chat_proto_init() }
func file_kama_chat_proto_init() {
	if File_kama_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kama_chat_proto_rawDesc), len(file_kama_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kama_chat_proto_goTypes,
		DependencyIndexes: file_kama_chat_proto_depIdxs,
		MessageInfos:      file_kama_chat_proto_msgTypes,
	}.Build()
	File_kama_chat_proto = out.File
	file_kama_chat_proto_goTypes = nil
	file_kama_chat_proto_depIdxs = nil
}
