// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: kama_chat.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Push_Push_FullMethodName = "/pb.Push/push"
)

// PushClient is the client API for Push service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*Response, error)
}

type pushClient struct {
	cc grpc.ClientConnInterface
}

func NewPushClient(cc grpc.ClientConnInterface) PushClient {
	return &pushClient{cc}
}

func (c *pushClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Push_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServer is the server API for Push service.
// All implementations must embed UnimplementedPushServer
// for forward compatibility.
type PushServer interface {
	Push(context.Context, *PushRequest) (*Response, error)
	mustEmbedUnimplementedPushServer()
}

// UnimplementedPushServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushServer struct{}

func (UnimplementedPushServer) Push(context.Context, *PushRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedPushServer) mustEmbedUnimplementedPushServer() {}
func (UnimplementedPushServer) testEmbeddedByValue()              {}

// UnsafePushServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServer will
// result in compilation errors.
type UnsafePushServer interface {
	mustEmbedUnimplementedPushServer()
}

func RegisterPushServer(s grpc.ServiceRegistrar, srv PushServer) {
	// If the following call panics, it indicates UnimplementedPushServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Push_ServiceDesc, srv)
}

func _Push_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Push_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Push_ServiceDesc is the grpc.ServiceDesc for Push service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Push_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Push",
	HandlerType: (*PushServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "push",
			Handler:    _Push_Push_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kama_chat.proto",
}

const (
	KamaChat_GetMessageBySeq_FullMethodName     = "/pb.KamaChat/getMessageBySeq"
	KamaChat_GetConversationList_FullMethodName = "/pb.KamaChat/getConversationList"
	KamaChat_Register_FullMethodName            = "/pb.KamaChat/register"
	KamaChat_Login_FullMethodName               = "/pb.KamaChat/login"
	KamaChat_GetFriendList_FullMethodName       = "/pb.KamaChat/getFriendList"
	KamaChat_ApplyFriend_FullMethodName         = "/pb.KamaChat/applyFriend"
	KamaChat_GetApplyList_FullMethodName        = "/pb.KamaChat/getApplyList"
	KamaChat_RespondToApply_FullMethodName      = "/pb.KamaChat/respondToApply"
)

// KamaChatClient is the client API for KamaChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KamaChatClient interface {
	GetMessageBySeq(ctx context.Context, in *GetMessageBySeqRequest, opts ...grpc.CallOption) (*ResponseForGetMessageBySeq, error)
	GetConversationList(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*ResponseForGetConversationList, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetFriendList(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*RespondForGetFriendList, error)
	ApplyFriend(ctx context.Context, in *ApplyFriendRequest, opts ...grpc.CallOption) (*Response, error)
	GetApplyList(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*ResponseForApplyList, error)
	RespondToApply(ctx context.Context, in *RespondToApply, opts ...grpc.CallOption) (*Response, error)
}

type kamaChatClient struct {
	cc grpc.ClientConnInterface
}

func NewKamaChatClient(cc grpc.ClientConnInterface) KamaChatClient {
	return &kamaChatClient{cc}
}

func (c *kamaChatClient) GetMessageBySeq(ctx context.Context, in *GetMessageBySeqRequest, opts ...grpc.CallOption) (*ResponseForGetMessageBySeq, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGetMessageBySeq)
	err := c.cc.Invoke(ctx, KamaChat_GetMessageBySeq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaChatClient) GetConversationList(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*ResponseForGetConversationList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGetConversationList)
	err := c.cc.Invoke(ctx, KamaChat_GetConversationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaChatClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, KamaChat_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaChatClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, KamaChat_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaChatClient) GetFriendList(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*RespondForGetFriendList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RespondForGetFriendList)
	err := c.cc.Invoke(ctx, KamaChat_GetFriendList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaChatClient) ApplyFriend(ctx context.Context, in *ApplyFriendRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KamaChat_ApplyFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaChatClient) GetApplyList(ctx context.Context, in *UserIdRequest, opts ...grpc.CallOption) (*ResponseForApplyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForApplyList)
	err := c.cc.Invoke(ctx, KamaChat_GetApplyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kamaChatClient) RespondToApply(ctx context.Context, in *RespondToApply, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KamaChat_RespondToApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KamaChatServer is the server API for KamaChat service.
// All implementations must embed UnimplementedKamaChatServer
// for forward compatibility.
type KamaChatServer interface {
	GetMessageBySeq(context.Context, *GetMessageBySeqRequest) (*ResponseForGetMessageBySeq, error)
	GetConversationList(context.Context, *UserIdRequest) (*ResponseForGetConversationList, error)
	Register(context.Context, *RegisterRequest) (*UserResponse, error)
	Login(context.Context, *LoginRequest) (*UserResponse, error)
	GetFriendList(context.Context, *UserIdRequest) (*RespondForGetFriendList, error)
	ApplyFriend(context.Context, *ApplyFriendRequest) (*Response, error)
	GetApplyList(context.Context, *UserIdRequest) (*ResponseForApplyList, error)
	RespondToApply(context.Context, *RespondToApply) (*Response, error)
	mustEmbedUnimplementedKamaChatServer()
}

// UnimplementedKamaChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKamaChatServer struct{}

func (UnimplementedKamaChatServer) GetMessageBySeq(context.Context, *GetMessageBySeqRequest) (*ResponseForGetMessageBySeq, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageBySeq not implemented")
}
func (UnimplementedKamaChatServer) GetConversationList(context.Context, *UserIdRequest) (*ResponseForGetConversationList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversationList not implemented")
}
func (UnimplementedKamaChatServer) Register(context.Context, *RegisterRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedKamaChatServer) Login(context.Context, *LoginRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedKamaChatServer) GetFriendList(context.Context, *UserIdRequest) (*RespondForGetFriendList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendList not implemented")
}
func (UnimplementedKamaChatServer) ApplyFriend(context.Context, *ApplyFriendRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyFriend not implemented")
}
func (UnimplementedKamaChatServer) GetApplyList(context.Context, *UserIdRequest) (*ResponseForApplyList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplyList not implemented")
}
func (UnimplementedKamaChatServer) RespondToApply(context.Context, *RespondToApply) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondToApply not implemented")
}
func (UnimplementedKamaChatServer) mustEmbedUnimplementedKamaChatServer() {}
func (UnimplementedKamaChatServer) testEmbeddedByValue()                  {}

// UnsafeKamaChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KamaChatServer will
// result in compilation errors.
type UnsafeKamaChatServer interface {
	mustEmbedUnimplementedKamaChatServer()
}

func RegisterKamaChatServer(s grpc.ServiceRegistrar, srv KamaChatServer) {
	// If the following call panics, it indicates UnimplementedKamaChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KamaChat_ServiceDesc, srv)
}

func _KamaChat_GetMessageBySeq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageBySeqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaChatServer).GetMessageBySeq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaChat_GetMessageBySeq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaChatServer).GetMessageBySeq(ctx, req.(*GetMessageBySeqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaChat_GetConversationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaChatServer).GetConversationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaChat_GetConversationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaChatServer).GetConversationList(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaChat_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaChatServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaChat_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaChatServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaChat_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaChatServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaChat_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaChatServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaChat_GetFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaChatServer).GetFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaChat_GetFriendList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaChatServer).GetFriendList(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaChat_ApplyFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaChatServer).ApplyFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaChat_ApplyFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaChatServer).ApplyFriend(ctx, req.(*ApplyFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaChat_GetApplyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaChatServer).GetApplyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaChat_GetApplyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaChatServer).GetApplyList(ctx, req.(*UserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KamaChat_RespondToApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RespondToApply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KamaChatServer).RespondToApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KamaChat_RespondToApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KamaChatServer).RespondToApply(ctx, req.(*RespondToApply))
	}
	return interceptor(ctx, in, info, handler)
}

// KamaChat_ServiceDesc is the grpc.ServiceDesc for KamaChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KamaChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.KamaChat",
	HandlerType: (*KamaChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getMessageBySeq",
			Handler:    _KamaChat_GetMessageBySeq_Handler,
		},
		{
			MethodName: "getConversationList",
			Handler:    _KamaChat_GetConversationList_Handler,
		},
		{
			MethodName: "register",
			Handler:    _KamaChat_Register_Handler,
		},
		{
			MethodName: "login",
			Handler:    _KamaChat_Login_Handler,
		},
		{
			MethodName: "getFriendList",
			Handler:    _KamaChat_GetFriendList_Handler,
		},
		{
			MethodName: "applyFriend",
			Handler:    _KamaChat_ApplyFriend_Handler,
		},
		{
			MethodName: "getApplyList",
			Handler:    _KamaChat_GetApplyList_Handler,
		},
		{
			MethodName: "respondToApply",
			Handler:    _KamaChat_RespondToApply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kama_chat.proto",
}
